name: dev workflow

on:
  push:
    branches: [main, develop]

jobs:
  test:
    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
        include:
          - miniforge-variant: Mambaforge
            miniforge-version: 4.11.0-4
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}

      - name: install dependencies
        run: pip install tox tox-gh-actions

      - name: test with tox
        run: tox
        env:
          CONDA_EXE: mamba

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: list files
        run: ls -l .

  publish_dev_build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: list files
        run: ls -l .

      - name: build wheels and source tarball
        run: |
          python -m build
          twine check --strict dist/*

      - name: publish to test pypi
        uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'push' # This step will only run on pushes
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
