name: tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            pip

      - name: install dependencies
        run: pip install tox tox-gh-actions

      - name: test with tox
        run: tox
        env:
          CONDA_EXE: mamba

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: list files
        run: ls -l .
