name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        include:
          - os: macos-latest
            python-version: "3.12"
          - os: windows-latest
            python-version: "3.12"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            pip

      - name: install dependencies
        run: pip install pdm nox

      - name: test with nox
        run: nox

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Test notebooks
        run: |
          git clone https://github.com/martibosch/pylandstats-notebooks
          cd pylandstats-notebooks
          mamba env update -f environment.yml
          snakemake -c1 register_ipykernel
          snakemake -c1 lulc_tifs elev_zones
          snakemake -c1 run_notebooks
          cd ..

      - name: list files
        run: ls -l .
